version: "3"

services:

  web:

    image: hanter/user-admin-server:0.0.2

    deploy:

      replicas: 2

      resources:

        limits:

          cpus: "0.1"

          memory: 50M

      restart_policy:

        condition: on-failure

    ports:

      - "18081:80"

    networks:

      - webnet

networks:

  webnet: